cp ./apps/barnes/BARNES ./bins/BARNES
cp ./kernels/cholesky/CHOLESKY ./bins/CHOLESKY
cp ./kernels/fft/FFT ./bins/FFT
cp ./apps/fmm/FMM ./bins/FMM
cp ./kernels/lu/contiguous_blocks/LU ./bins/LU-CONT
cp ./kernels/lu/non_contiguous_blocks/LU ./bins/LU-NOCONT
cp ./apps/ocean/contiguous_partitions/OCEAN ./bins/OCEAN-CONT
cp ./apps/ocean/non_contiguous_partitions/OCEAN ./bins/OCEAN-NOCONT
cp ./apps/radiosity/RADIOSITY ./bins/RADIOSITY
cp ./kernels/radix/RADIX ./bins/RADIX
cp ./apps/raytrace/RAYTRACE ./bins/RAYTRACE
cp ./apps/volrend/VOLREND ./bins/VOLREND
cp ./apps/water-nsquared/WATER-NSQUARED ./bins/WATER-NSQUARED
cp ./apps/water-spatial/WATER-SPATIAL ./bins/WATER-SPATIAL
