# Cross-compile changes by Thomas E. Hansen (CodingCellist) 2021-03-08

mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
current_dir := $(dir $(mkfile_path))

CC := $(TOOLCHAIN_PREFIX)gcc
CFLAGS := -O2 -pthread -D_XOPEN_SOURCE=500 -D_POSIX_C_SOURCE=200112 -std=c11 -g -fno-strict-aliasing -I$(current_dir)/hooks_m5 -I$(current_dir)/hooks_m5/include -DENABLE_PARSEC_HOOKS -DRESET_STATS -DBIND_THREADS
LDFLAGS := -L$(current_dir)/hooks_m5/.libs -lm -lhooks

# BASEDIR needs to be set to the same directory as this Makefile
# BASEDIR := $(HOME)/Splash-3/codes
BASEDIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
MACROS := $(BASEDIR)/pthread_macros/pthread.m4.stougie
M4 := m4 -Ulen -Uindex

ifndef BASEDIR
$(error Please define the BASEDIR variable)
endif

x = *

$(TARGET): $(OBJS) $(EXTRADEPS)
	$(CC) $(current_dir)/hooks_m5/m5op_x86.o $(CFLAGS) -o $(TARGET) $(OBJS) $(LDFLAGS)

clean:
	rm -rf *.c *.h *.o $(TARGET)

%.h: %.h.in
	$(M4) $(MACROS) $< > $@

%.c: %.c.in
	$(M4) $(MACROS) $< > $@

%.o: %.c $(EXTRADEPS)
	$(CC) -c $(CFLAGS) $<
